# SPDX-License-Identifier: Zlib
#
# Generated from third_party/libretro-fceumm/Makefile.libretro by scripts/gen-core-mk.py.
# Edit the generator, not this file, then re-run it.

fceumm_DIR := third_party/libretro-fceumm
fceumm_EXTS := nes fds

fceumm_SRCS := \
    third_party/libretro-fceumm/src/boards/__dummy_mapper.c \
    third_party/libretro-fceumm/src/boards/__serial.c \
    third_party/libretro-fceumm/src/boards/09-034a.c \
    third_party/libretro-fceumm/src/boards/103.c \
    third_party/libretro-fceumm/src/boards/104.c \
    third_party/libretro-fceumm/src/boards/106.c \
    third_party/libretro-fceumm/src/boards/108.c \
    third_party/libretro-fceumm/src/boards/112.c \
    third_party/libretro-fceumm/src/boards/116.c \
    third_party/libretro-fceumm/src/boards/117.c \
    third_party/libretro-fceumm/src/boards/120.c \
    third_party/libretro-fceumm/src/boards/121.c \
    third_party/libretro-fceumm/src/boards/122.c \
    third_party/libretro-fceumm/src/boards/126_422_534.c \
    third_party/libretro-fceumm/src/boards/128.c \
    third_party/libretro-fceumm/src/boards/12in1.c \
    third_party/libretro-fceumm/src/boards/134.c \
    third_party/libretro-fceumm/src/boards/14.c \
    third_party/libretro-fceumm/src/boards/15.c \
    third_party/libretro-fceumm/src/boards/151.c \
    third_party/libretro-fceumm/src/boards/156.c \
    third_party/libretro-fceumm/src/boards/162.c \
    third_party/libretro-fceumm/src/boards/163.c \
    third_party/libretro-fceumm/src/boards/164.c \
    third_party/libretro-fceumm/src/boards/168.c \
    third_party/libretro-fceumm/src/boards/170.c \
    third_party/libretro-fceumm/src/boards/174.c \
    third_party/libretro-fceumm/src/boards/175.c \
    third_party/libretro-fceumm/src/boards/177.c \
    third_party/libretro-fceumm/src/boards/178.c \
    third_party/libretro-fceumm/src/boards/18.c \
    third_party/libretro-fceumm/src/boards/182.c \
    third_party/libretro-fceumm/src/boards/183.c \
    third_party/libretro-fceumm/src/boards/185.c \
    third_party/libretro-fceumm/src/boards/186.c \
    third_party/libretro-fceumm/src/boards/187.c \
    third_party/libretro-fceumm/src/boards/189.c \
    third_party/libretro-fceumm/src/boards/190.c \
    third_party/libretro-fceumm/src/boards/191.c \
    third_party/libretro-fceumm/src/boards/193.c \
    third_party/libretro-fceumm/src/boards/195.c \
    third_party/libretro-fceumm/src/boards/199.c \
    third_party/libretro-fceumm/src/boards/206_486.c \
    third_party/libretro-fceumm/src/boards/208.c \
    third_party/libretro-fceumm/src/boards/21_22_23_25.c \
    third_party/libretro-fceumm/src/boards/213.c \
    third_party/libretro-fceumm/src/boards/218.c \
    third_party/libretro-fceumm/src/boards/222.c \
    third_party/libretro-fceumm/src/boards/225.c \
    third_party/libretro-fceumm/src/boards/228.c \
    third_party/libretro-fceumm/src/boards/230.c \
    third_party/libretro-fceumm/src/boards/232.c \
    third_party/libretro-fceumm/src/boards/233.c \
    third_party/libretro-fceumm/src/boards/234.c \
    third_party/libretro-fceumm/src/boards/235.c \
    third_party/libretro-fceumm/src/boards/236.c \
    third_party/libretro-fceumm/src/boards/237.c \
    third_party/libretro-fceumm/src/boards/239.c \
    third_party/libretro-fceumm/src/boards/242.c \
    third_party/libretro-fceumm/src/boards/244.c \
    third_party/libretro-fceumm/src/boards/246.c \
    third_party/libretro-fceumm/src/boards/252_253.c \
    third_party/libretro-fceumm/src/boards/265.c \
    third_party/libretro-fceumm/src/boards/266.c \
    third_party/libretro-fceumm/src/boards/267.c \
    third_party/libretro-fceumm/src/boards/268.c \
    third_party/libretro-fceumm/src/boards/269.c \
    third_party/libretro-fceumm/src/boards/272.c \
    third_party/libretro-fceumm/src/boards/273.c \
    third_party/libretro-fceumm/src/boards/277.c \
    third_party/libretro-fceumm/src/boards/28.c \
    third_party/libretro-fceumm/src/boards/280.c \
    third_party/libretro-fceumm/src/boards/283.c \
    third_party/libretro-fceumm/src/boards/285.c \
    third_party/libretro-fceumm/src/boards/291.c \
    third_party/libretro-fceumm/src/boards/293.c \
    third_party/libretro-fceumm/src/boards/294.c \
    third_party/libretro-fceumm/src/boards/298.c \
    third_party/libretro-fceumm/src/boards/301.c \
    third_party/libretro-fceumm/src/boards/308.c \
    third_party/libretro-fceumm/src/boards/31.c \
    third_party/libretro-fceumm/src/boards/310.c \
    third_party/libretro-fceumm/src/boards/319.c \
    third_party/libretro-fceumm/src/boards/32.c \
    third_party/libretro-fceumm/src/boards/321.c \
    third_party/libretro-fceumm/src/boards/326.c \
    third_party/libretro-fceumm/src/boards/33.c \
    third_party/libretro-fceumm/src/boards/330.c \
    third_party/libretro-fceumm/src/boards/334.c \
    third_party/libretro-fceumm/src/boards/34.c \
    third_party/libretro-fceumm/src/boards/340.c \
    third_party/libretro-fceumm/src/boards/341.c \
    third_party/libretro-fceumm/src/boards/343.c \
    third_party/libretro-fceumm/src/boards/351.c \
    third_party/libretro-fceumm/src/boards/352.c \
    third_party/libretro-fceumm/src/boards/353.c \
    third_party/libretro-fceumm/src/boards/354.c \
    third_party/libretro-fceumm/src/boards/355.c \
    third_party/libretro-fceumm/src/boards/356.c \
    third_party/libretro-fceumm/src/boards/357.c \
    third_party/libretro-fceumm/src/boards/359.c \
    third_party/libretro-fceumm/src/boards/360.c \
    third_party/libretro-fceumm/src/boards/361.c \
    third_party/libretro-fceumm/src/boards/362.c \
    third_party/libretro-fceumm/src/boards/363.c \
    third_party/libretro-fceumm/src/boards/364.c \
    third_party/libretro-fceumm/src/boards/366.c \
    third_party/libretro-fceumm/src/boards/368.c \
    third_party/libretro-fceumm/src/boards/369.c \
    third_party/libretro-fceumm/src/boards/370.c \
    third_party/libretro-fceumm/src/boards/372.c \
    third_party/libretro-fceumm/src/boards/375.c \
    third_party/libretro-fceumm/src/boards/376.c \
    third_party/libretro-fceumm/src/boards/377.c \
    third_party/libretro-fceumm/src/boards/378.c \
    third_party/libretro-fceumm/src/boards/379.c \
    third_party/libretro-fceumm/src/boards/380.c \
    third_party/libretro-fceumm/src/boards/382.c \
    third_party/libretro-fceumm/src/boards/383.c \
    third_party/libretro-fceumm/src/boards/384.c \
    third_party/libretro-fceumm/src/boards/389.c \
    third_party/libretro-fceumm/src/boards/390.c \
    third_party/libretro-fceumm/src/boards/391.c \
    third_party/libretro-fceumm/src/boards/393.c \
    third_party/libretro-fceumm/src/boards/395.c \
    third_party/libretro-fceumm/src/boards/396.c \
    third_party/libretro-fceumm/src/boards/398.c \
    third_party/libretro-fceumm/src/boards/399.c \
    third_party/libretro-fceumm/src/boards/40.c \
    third_party/libretro-fceumm/src/boards/400.c \
    third_party/libretro-fceumm/src/boards/401.c \
    third_party/libretro-fceumm/src/boards/403.c \
    third_party/libretro-fceumm/src/boards/406.c \
    third_party/libretro-fceumm/src/boards/41.c \
    third_party/libretro-fceumm/src/boards/410.c \
    third_party/libretro-fceumm/src/boards/411.c \
    third_party/libretro-fceumm/src/boards/411120-c.c \
    third_party/libretro-fceumm/src/boards/412.c \
    third_party/libretro-fceumm/src/boards/413.c \
    third_party/libretro-fceumm/src/boards/414.c \
    third_party/libretro-fceumm/src/boards/416.c \
    third_party/libretro-fceumm/src/boards/417.c \
    third_party/libretro-fceumm/src/boards/418.c \
    third_party/libretro-fceumm/src/boards/42.c \
    third_party/libretro-fceumm/src/boards/420.c \
    third_party/libretro-fceumm/src/boards/428.c \
    third_party/libretro-fceumm/src/boards/43.c \
    third_party/libretro-fceumm/src/boards/430.c \
    third_party/libretro-fceumm/src/boards/431.c \
    third_party/libretro-fceumm/src/boards/432.c \
    third_party/libretro-fceumm/src/boards/433.c \
    third_party/libretro-fceumm/src/boards/434.c \
    third_party/libretro-fceumm/src/boards/437.c \
    third_party/libretro-fceumm/src/boards/438.c \
    third_party/libretro-fceumm/src/boards/439.c \
    third_party/libretro-fceumm/src/boards/441.c \
    third_party/libretro-fceumm/src/boards/443.c \
    third_party/libretro-fceumm/src/boards/444.c \
    third_party/libretro-fceumm/src/boards/445.c \
    third_party/libretro-fceumm/src/boards/446.c \
    third_party/libretro-fceumm/src/boards/447.c \
    third_party/libretro-fceumm/src/boards/448.c \
    third_party/libretro-fceumm/src/boards/449.c \
    third_party/libretro-fceumm/src/boards/450.c \
    third_party/libretro-fceumm/src/boards/451.c \
    third_party/libretro-fceumm/src/boards/452.c \
    third_party/libretro-fceumm/src/boards/453.c \
    third_party/libretro-fceumm/src/boards/454.c \
    third_party/libretro-fceumm/src/boards/455.c \
    third_party/libretro-fceumm/src/boards/456.c \
    third_party/libretro-fceumm/src/boards/457.c \
    third_party/libretro-fceumm/src/boards/458.c \
    third_party/libretro-fceumm/src/boards/46.c \
    third_party/libretro-fceumm/src/boards/460.c \
    third_party/libretro-fceumm/src/boards/461.c \
    third_party/libretro-fceumm/src/boards/463.c \
    third_party/libretro-fceumm/src/boards/465.c \
    third_party/libretro-fceumm/src/boards/466.c \
    third_party/libretro-fceumm/src/boards/467.c \
    third_party/libretro-fceumm/src/boards/468.c \
    third_party/libretro-fceumm/src/boards/471.c \
    third_party/libretro-fceumm/src/boards/473.c \
    third_party/libretro-fceumm/src/boards/474.c \
    third_party/libretro-fceumm/src/boards/475.c \
    third_party/libretro-fceumm/src/boards/476.c \
    third_party/libretro-fceumm/src/boards/478.c \
    third_party/libretro-fceumm/src/boards/480.c \
    third_party/libretro-fceumm/src/boards/482.c \
    third_party/libretro-fceumm/src/boards/483.c \
    third_party/libretro-fceumm/src/boards/484.c \
    third_party/libretro-fceumm/src/boards/485.c \
    third_party/libretro-fceumm/src/boards/487.c \
    third_party/libretro-fceumm/src/boards/489.c \
    third_party/libretro-fceumm/src/boards/490.c \
    third_party/libretro-fceumm/src/boards/491.c \
    third_party/libretro-fceumm/src/boards/492.c \
    third_party/libretro-fceumm/src/boards/493.c \
    third_party/libretro-fceumm/src/boards/494.c \
    third_party/libretro-fceumm/src/boards/495.c \
    third_party/libretro-fceumm/src/boards/498.c \
    third_party/libretro-fceumm/src/boards/499.c \
    third_party/libretro-fceumm/src/boards/50.c \
    third_party/libretro-fceumm/src/boards/500.c \
    third_party/libretro-fceumm/src/boards/501.c \
    third_party/libretro-fceumm/src/boards/502.c \
    third_party/libretro-fceumm/src/boards/503.c \
    third_party/libretro-fceumm/src/boards/504.c \
    third_party/libretro-fceumm/src/boards/505.c \
    third_party/libretro-fceumm/src/boards/506.c \
    third_party/libretro-fceumm/src/boards/507.c \
    third_party/libretro-fceumm/src/boards/508.c \
    third_party/libretro-fceumm/src/boards/509.c \
    third_party/libretro-fceumm/src/boards/51.c \
    third_party/libretro-fceumm/src/boards/510.c \
    third_party/libretro-fceumm/src/boards/511.c \
    third_party/libretro-fceumm/src/boards/512.c \
    third_party/libretro-fceumm/src/boards/514.c \
    third_party/libretro-fceumm/src/boards/516.c \
    third_party/libretro-fceumm/src/boards/518.c \
    third_party/libretro-fceumm/src/boards/520.c \
    third_party/libretro-fceumm/src/boards/524.c \
    third_party/libretro-fceumm/src/boards/525.c \
    third_party/libretro-fceumm/src/boards/527.c \
    third_party/libretro-fceumm/src/boards/528.c \
    third_party/libretro-fceumm/src/boards/529.c \
    third_party/libretro-fceumm/src/boards/530.c \
    third_party/libretro-fceumm/src/boards/533.c \
    third_party/libretro-fceumm/src/boards/536.c \
    third_party/libretro-fceumm/src/boards/537.c \
    third_party/libretro-fceumm/src/boards/539.c \
    third_party/libretro-fceumm/src/boards/542.c \
    third_party/libretro-fceumm/src/boards/544.c \
    third_party/libretro-fceumm/src/boards/545.c \
    third_party/libretro-fceumm/src/boards/546.c \
    third_party/libretro-fceumm/src/boards/548.c \
    third_party/libretro-fceumm/src/boards/549.c \
    third_party/libretro-fceumm/src/boards/554.c \
    third_party/libretro-fceumm/src/boards/556.c \
    third_party/libretro-fceumm/src/boards/557.c \
    third_party/libretro-fceumm/src/boards/558.c \
    third_party/libretro-fceumm/src/boards/559.c \
    third_party/libretro-fceumm/src/boards/563.c \
    third_party/libretro-fceumm/src/boards/564.c \
    third_party/libretro-fceumm/src/boards/565.c \
    third_party/libretro-fceumm/src/boards/566.c \
    third_party/libretro-fceumm/src/boards/567.c \
    third_party/libretro-fceumm/src/boards/568.c \
    third_party/libretro-fceumm/src/boards/569.c \
    third_party/libretro-fceumm/src/boards/57.c \
    third_party/libretro-fceumm/src/boards/570.c \
    third_party/libretro-fceumm/src/boards/571.c \
    third_party/libretro-fceumm/src/boards/572.c \
    third_party/libretro-fceumm/src/boards/573.c \
    third_party/libretro-fceumm/src/boards/574.c \
    third_party/libretro-fceumm/src/boards/575.c \
    third_party/libretro-fceumm/src/boards/576.c \
    third_party/libretro-fceumm/src/boards/577.c \
    third_party/libretro-fceumm/src/boards/578.c \
    third_party/libretro-fceumm/src/boards/579.c \
    third_party/libretro-fceumm/src/boards/580.c \
    third_party/libretro-fceumm/src/boards/581.c \
    third_party/libretro-fceumm/src/boards/582.c \
    third_party/libretro-fceumm/src/boards/583.c \
    third_party/libretro-fceumm/src/boards/584.c \
    third_party/libretro-fceumm/src/boards/585.c \
    third_party/libretro-fceumm/src/boards/586.c \
    third_party/libretro-fceumm/src/boards/587.c \
    third_party/libretro-fceumm/src/boards/588.c \
    third_party/libretro-fceumm/src/boards/589.c \
    third_party/libretro-fceumm/src/boards/590.c \
    third_party/libretro-fceumm/src/boards/591.c \
    third_party/libretro-fceumm/src/boards/592.c \
    third_party/libretro-fceumm/src/boards/594.c \
    third_party/libretro-fceumm/src/boards/595.c \
    third_party/libretro-fceumm/src/boards/596.c \
    third_party/libretro-fceumm/src/boards/597.c \
    third_party/libretro-fceumm/src/boards/598.c \
    third_party/libretro-fceumm/src/boards/599.c \
    third_party/libretro-fceumm/src/boards/6_8_12_17_561_562.c \
    third_party/libretro-fceumm/src/boards/60.c \
    third_party/libretro-fceumm/src/boards/603-5052.c \
    third_party/libretro-fceumm/src/boards/603.c \
    third_party/libretro-fceumm/src/boards/605.c \
    third_party/libretro-fceumm/src/boards/606.c \
    third_party/libretro-fceumm/src/boards/607.c \
    third_party/libretro-fceumm/src/boards/608.c \
    third_party/libretro-fceumm/src/boards/609.c \
    third_party/libretro-fceumm/src/boards/610.c \
    third_party/libretro-fceumm/src/boards/611.c \
    third_party/libretro-fceumm/src/boards/612.c \
    third_party/libretro-fceumm/src/boards/613.c \
    third_party/libretro-fceumm/src/boards/614.c \
    third_party/libretro-fceumm/src/boards/615.c \
    third_party/libretro-fceumm/src/boards/616.c \
    third_party/libretro-fceumm/src/boards/617.c \
    third_party/libretro-fceumm/src/boards/618.c \
    third_party/libretro-fceumm/src/boards/619.c \
    third_party/libretro-fceumm/src/boards/62.c \
    third_party/libretro-fceumm/src/boards/620.c \
    third_party/libretro-fceumm/src/boards/621.c \
    third_party/libretro-fceumm/src/boards/622.c \
    third_party/libretro-fceumm/src/boards/623.c \
    third_party/libretro-fceumm/src/boards/624.c \
    third_party/libretro-fceumm/src/boards/625.c \
    third_party/libretro-fceumm/src/boards/65.c \
    third_party/libretro-fceumm/src/boards/67.c \
    third_party/libretro-fceumm/src/boards/68.c \
    third_party/libretro-fceumm/src/boards/69.c \
    third_party/libretro-fceumm/src/boards/71.c \
    third_party/libretro-fceumm/src/boards/72.c \
    third_party/libretro-fceumm/src/boards/77.c \
    third_party/libretro-fceumm/src/boards/79.c \
    third_party/libretro-fceumm/src/boards/80.c \
    third_party/libretro-fceumm/src/boards/81.c \
    third_party/libretro-fceumm/src/boards/82_552.c \
    third_party/libretro-fceumm/src/boards/8237.c \
    third_party/libretro-fceumm/src/boards/83_264.c \
    third_party/libretro-fceumm/src/boards/830118C.c \
    third_party/libretro-fceumm/src/boards/830134C.c \
    third_party/libretro-fceumm/src/boards/88.c \
    third_party/libretro-fceumm/src/boards/8in1.c \
    third_party/libretro-fceumm/src/boards/91.c \
    third_party/libretro-fceumm/src/boards/96.c \
    third_party/libretro-fceumm/src/boards/99.c \
    third_party/libretro-fceumm/src/boards/a9746.c \
    third_party/libretro-fceumm/src/boards/ac-08.c \
    third_party/libretro-fceumm/src/boards/addrlatch.c \
    third_party/libretro-fceumm/src/boards/asic_fme7.c \
    third_party/libretro-fceumm/src/boards/asic_h3001.c \
    third_party/libretro-fceumm/src/boards/asic_latch.c \
    third_party/libretro-fceumm/src/boards/asic_mmc1.c \
    third_party/libretro-fceumm/src/boards/asic_mmc2and4.c \
    third_party/libretro-fceumm/src/boards/asic_mmc3.c \
    third_party/libretro-fceumm/src/boards/asic_n118.c \
    third_party/libretro-fceumm/src/boards/asic_pt8154.c \
    third_party/libretro-fceumm/src/boards/asic_qj.c \
    third_party/libretro-fceumm/src/boards/asic_tc3294.c \
    third_party/libretro-fceumm/src/boards/asic_vrc1.c \
    third_party/libretro-fceumm/src/boards/asic_vrc2and4.c \
    third_party/libretro-fceumm/src/boards/asic_vrc3.c \
    third_party/libretro-fceumm/src/boards/asic_vrc6.c \
    third_party/libretro-fceumm/src/boards/asic_vrc7.c \
    third_party/libretro-fceumm/src/boards/bandai.c \
    third_party/libretro-fceumm/src/boards/bb.c \
    third_party/libretro-fceumm/src/boards/bj56.c \
    third_party/libretro-fceumm/src/boards/bmc42in1r.c \
    third_party/libretro-fceumm/src/boards/bmc60311c.c \
    third_party/libretro-fceumm/src/boards/bmc64in1nr.c \
    third_party/libretro-fceumm/src/boards/bmc80013b.c \
    third_party/libretro-fceumm/src/boards/bmc830425C4391t.c \
    third_party/libretro-fceumm/src/boards/bmcctc09.c \
    third_party/libretro-fceumm/src/boards/bmcgamecard.c \
    third_party/libretro-fceumm/src/boards/bmck3006.c \
    third_party/libretro-fceumm/src/boards/bmck3033.c \
    third_party/libretro-fceumm/src/boards/bmcl6in1.c \
    third_party/libretro-fceumm/src/boards/BMW8544.c \
    third_party/libretro-fceumm/src/boards/bonza.c \
    third_party/libretro-fceumm/src/boards/bs-5.c \
    third_party/libretro-fceumm/src/boards/cartram.c \
    third_party/libretro-fceumm/src/boards/cheapocabra.c \
    third_party/libretro-fceumm/src/boards/coolgirl.c \
    third_party/libretro-fceumm/src/boards/datalatch.c \
    third_party/libretro-fceumm/src/boards/dream.c \
    third_party/libretro-fceumm/src/boards/edu2000.c \
    third_party/libretro-fceumm/src/boards/eeprom_93Cx6.c \
    third_party/libretro-fceumm/src/boards/eh8813a.c \
    third_party/libretro-fceumm/src/boards/emu2413.c \
    third_party/libretro-fceumm/src/boards/et-100.c \
    third_party/libretro-fceumm/src/boards/et-4320.c \
    third_party/libretro-fceumm/src/boards/f-15.c \
    third_party/libretro-fceumm/src/boards/famicombox.c \
    third_party/libretro-fceumm/src/boards/faridunrom.c \
    third_party/libretro-fceumm/src/boards/fifo.c \
    third_party/libretro-fceumm/src/boards/fk23c.c \
    third_party/libretro-fceumm/src/boards/flashrom.c \
    third_party/libretro-fceumm/src/boards/gn26.c \
    third_party/libretro-fceumm/src/boards/h2288.c \
    third_party/libretro-fceumm/src/boards/hp10xx_hp20xx.c \
    third_party/libretro-fceumm/src/boards/hp898f.c \
    third_party/libretro-fceumm/src/boards/inx007t.c \
    third_party/libretro-fceumm/src/boards/jyasic.c \
    third_party/libretro-fceumm/src/boards/karaoke.c \
    third_party/libretro-fceumm/src/boards/KG256.c \
    third_party/libretro-fceumm/src/boards/kof97.c \
    third_party/libretro-fceumm/src/boards/KS7012.c \
    third_party/libretro-fceumm/src/boards/KS7013.c \
    third_party/libretro-fceumm/src/boards/KS7016.c \
    third_party/libretro-fceumm/src/boards/KS7017.c \
    third_party/libretro-fceumm/src/boards/KS7030.c \
    third_party/libretro-fceumm/src/boards/KS7031.c \
    third_party/libretro-fceumm/src/boards/KS7032.c \
    third_party/libretro-fceumm/src/boards/KS7037.c \
    third_party/libretro-fceumm/src/boards/KS7057.c \
    third_party/libretro-fceumm/src/boards/latch.c \
    third_party/libretro-fceumm/src/boards/le05.c \
    third_party/libretro-fceumm/src/boards/lh32.c \
    third_party/libretro-fceumm/src/boards/lh51.c \
    third_party/libretro-fceumm/src/boards/lh53.c \
    third_party/libretro-fceumm/src/boards/malee.c \
    third_party/libretro-fceumm/src/boards/mihunche.c \
    third_party/libretro-fceumm/src/boards/mmc1.c \
    third_party/libretro-fceumm/src/boards/mmc2and4.c \
    third_party/libretro-fceumm/src/boards/mmc3.c \
    third_party/libretro-fceumm/src/boards/mmc5.c \
    third_party/libretro-fceumm/src/boards/msm6585.c \
    third_party/libretro-fceumm/src/boards/n106.c \
    third_party/libretro-fceumm/src/boards/n625092.c \
    third_party/libretro-fceumm/src/boards/novel.c \
    third_party/libretro-fceumm/src/boards/onebus.c \
    third_party/libretro-fceumm/src/boards/pec-586.c \
    third_party/libretro-fceumm/src/boards/pic16c5x.c \
    third_party/libretro-fceumm/src/boards/resetnromxin1.c \
    third_party/libretro-fceumm/src/boards/resettxrom.c \
    third_party/libretro-fceumm/src/boards/rt-01.c \
    third_party/libretro-fceumm/src/boards/SA-9602B.c \
    third_party/libretro-fceumm/src/boards/sachen.c \
    third_party/libretro-fceumm/src/boards/sheroes.c \
    third_party/libretro-fceumm/src/boards/subor.c \
    third_party/libretro-fceumm/src/boards/super40in1.c \
    third_party/libretro-fceumm/src/boards/supervision.c \
    third_party/libretro-fceumm/src/boards/t-227-1.c \
    third_party/libretro-fceumm/src/boards/t-262.c \
    third_party/libretro-fceumm/src/boards/tengen.c \
    third_party/libretro-fceumm/src/boards/transformer.c \
    third_party/libretro-fceumm/src/boards/txcchip.c \
    third_party/libretro-fceumm/src/boards/unrom512.c \
    third_party/libretro-fceumm/src/boards/vrc1.c \
    third_party/libretro-fceumm/src/boards/vrc3.c \
    third_party/libretro-fceumm/src/boards/vrc6.c \
    third_party/libretro-fceumm/src/boards/vrc7.c \
    third_party/libretro-fceumm/src/boards/vrc7p.c \
    third_party/libretro-fceumm/src/boards/vrcirq.c \
    third_party/libretro-fceumm/src/input/arkanoid.c \
    third_party/libretro-fceumm/src/input/bbox.c \
    third_party/libretro-fceumm/src/input/bworld.c \
    third_party/libretro-fceumm/src/input/cursor.c \
    third_party/libretro-fceumm/src/input/fkb.c \
    third_party/libretro-fceumm/src/input/ftrainer.c \
    third_party/libretro-fceumm/src/input/hypershot.c \
    third_party/libretro-fceumm/src/input/mahjong.c \
    third_party/libretro-fceumm/src/input/mouse.c \
    third_party/libretro-fceumm/src/input/oekakids.c \
    third_party/libretro-fceumm/src/input/pec586kb.c \
    third_party/libretro-fceumm/src/input/powerpad.c \
    third_party/libretro-fceumm/src/input/quiz.c \
    third_party/libretro-fceumm/src/input/shadow.c \
    third_party/libretro-fceumm/src/input/suborkb.c \
    third_party/libretro-fceumm/src/input/toprider.c \
    third_party/libretro-fceumm/src/input/zapper.c \
    third_party/libretro-fceumm/src/ntsc/nes_ntsc.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro_dipswitch.c \
    third_party/libretro-fceumm/src/cart.c \
    third_party/libretro-fceumm/src/cheat.c \
    third_party/libretro-fceumm/src/crc32.c \
    third_party/libretro-fceumm/src/fceu-endian.c \
    third_party/libretro-fceumm/src/fceu-memory.c \
    third_party/libretro-fceumm/src/fceu.c \
    third_party/libretro-fceumm/src/fds.c \
    third_party/libretro-fceumm/src/fds_apu.c \
    third_party/libretro-fceumm/src/file.c \
    third_party/libretro-fceumm/src/filter.c \
    third_party/libretro-fceumm/src/general.c \
    third_party/libretro-fceumm/src/input.c \
    third_party/libretro-fceumm/src/md5.c \
    third_party/libretro-fceumm/src/nsf.c \
    third_party/libretro-fceumm/src/palette.c \
    third_party/libretro-fceumm/src/ppu.c \
    third_party/libretro-fceumm/src/sound.c \
    third_party/libretro-fceumm/src/state.c \
    third_party/libretro-fceumm/src/video.c \
    third_party/libretro-fceumm/src/vsuni.c \
    third_party/libretro-fceumm/src/ines.c \
    third_party/libretro-fceumm/src/unif.c \
    third_party/libretro-fceumm/src/x6502.c \
    third_party/libretro-fceumm/src/hdpack/hdpack_load.c \
    third_party/libretro-fceumm/src/hdpack/hdpack_image.c \
    third_party/libretro-fceumm/src/hdpack/hdpack_ppu.c \
    third_party/libretro-fceumm/src/hdpack/hdpack_render.c \
    third_party/libretro-fceumm/src/hdpack/hdpack_audio.c \
    third_party/libretro-fceumm/src/hdpack/hdpack_patch.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/formats/png/rpng.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/formats/dds/rdds.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/formats/webp/rwebp.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/formats/vp8/rvp8.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/formats/vorbis/rvorbis.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/formats/wav/rwav.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/streams/trans_stream.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/streams/trans_stream_pipe.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/streams/trans_stream_deflate.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/encodings/encoding_deflate.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/streams/memory_stream.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/compat/compat_posix_string.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/compat/compat_snprintf.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/compat/compat_strcasestr.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/compat/compat_strl.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/compat/fopen_utf8.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/encodings/encoding_utf.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/file/file_path.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/file/file_path_io.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/streams/file_stream.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/streams/file_stream_transforms.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/string/stdstring.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/time/rtime.c \
    third_party/libretro-fceumm/src/drivers/libretro/libretro-common/vfs/vfs_implementation.c

fceumm_DEFINES := \
    -DFCEU_VERSION_NUMERIC=9900 -DFRONTEND_SUPPORTS_RGB888 -DHAVE_HDPACK -DHAVE_NTSC_FILTER -DNDEBUG -DPATH_MAX=1024 -D__LIBRETRO__

fceumm_INCLUDES := \
    -Ithird_party/libretro-fceumm/src/drivers/libretro \
    -Ithird_party/libretro-fceumm/src/drivers/libretro/libretro-common/include \
    -Ithird_party/libretro-fceumm/src \
    -Ithird_party/libretro-fceumm/src/input \
    -Ithird_party/libretro-fceumm/src/boards \
    -Ithird_party/libretro-fceumm/src/ntsc

