# SPDX-License-Identifier: Zlib
#
# Generated from third_party/fuse-libretro/Makefile.libretro by scripts/gen-core-mk.py.
# Edit the generator, not this file, then re-run it.

fuse_DIR := third_party/fuse-libretro
fuse_EXTS := z80 tap sna tzx szx

fuse_SRCS := \
    third_party/fuse-libretro/src/libretro.c \
    third_party/fuse-libretro/src/coreopt.c \
    third_party/fuse-libretro/src/missing.c \
    third_party/fuse-libretro/src/version.c \
    third_party/fuse-libretro/src/compat/dir.c \
    third_party/fuse-libretro/src/compat/display.c \
    third_party/fuse-libretro/src/compat/fat.c \
    third_party/fuse-libretro/src/compat/file.c \
    third_party/fuse-libretro/src/compat/joystick.c \
    third_party/fuse-libretro/src/compat/keyboard.c \
    third_party/fuse-libretro/src/compat/mouse.c \
    third_party/fuse-libretro/src/compat/osname.c \
    third_party/fuse-libretro/src/compat/paths.c \
    third_party/fuse-libretro/src/compat/sound.c \
    third_party/fuse-libretro/src/compat/timer.c \
    third_party/fuse-libretro/src/compat/ui.c \
    third_party/fuse-libretro/fuse/infrastructure/startup_manager.c \
    third_party/fuse-libretro/fuse/debugger/breakpoint.c \
    third_party/fuse-libretro/fuse/debugger/command.c \
    third_party/fuse-libretro/fuse/debugger/commandl.c \
    third_party/fuse-libretro/fuse/debugger/commandy.c \
    third_party/fuse-libretro/fuse/debugger/debugger.c \
    third_party/fuse-libretro/fuse/debugger/disassemble.c \
    third_party/fuse-libretro/fuse/debugger/event.c \
    third_party/fuse-libretro/fuse/debugger/expression.c \
    third_party/fuse-libretro/fuse/debugger/variable.c \
    third_party/fuse-libretro/fuse/debugger/system_variable.c \
    third_party/fuse-libretro/fuse/machines/machines_periph.c \
    third_party/fuse-libretro/fuse/machines/pentagon.c \
    third_party/fuse-libretro/fuse/machines/pentagon512.c \
    third_party/fuse-libretro/fuse/machines/pentagon1024.c \
    third_party/fuse-libretro/fuse/machines/scorpion.c \
    third_party/fuse-libretro/fuse/machines/spec128.c \
    third_party/fuse-libretro/fuse/machines/spec16.c \
    third_party/fuse-libretro/fuse/machines/spec48.c \
    third_party/fuse-libretro/fuse/machines/spec48_ntsc.c \
    third_party/fuse-libretro/fuse/machines/specplus2.c \
    third_party/fuse-libretro/fuse/machines/spec_se.c \
    third_party/fuse-libretro/fuse/machines/specplus2a.c \
    third_party/fuse-libretro/fuse/machines/specplus3.c \
    third_party/fuse-libretro/fuse/machines/specplus3e.c \
    third_party/fuse-libretro/fuse/machines/tc2048.c \
    third_party/fuse-libretro/fuse/machines/tc2068.c \
    third_party/fuse-libretro/fuse/machines/ts2068.c \
    third_party/fuse-libretro/fuse/peripherals/disk/beta.c \
    third_party/fuse-libretro/fuse/peripherals/disk/crc.c \
    third_party/fuse-libretro/fuse/peripherals/disk/disciple.c \
    third_party/fuse-libretro/fuse/peripherals/disk/disk.c \
    third_party/fuse-libretro/fuse/peripherals/disk/fdd.c \
    third_party/fuse-libretro/fuse/peripherals/disk/opus.c \
    third_party/fuse-libretro/fuse/peripherals/disk/plusd.c \
    third_party/fuse-libretro/fuse/peripherals/disk/upd_fdc.c \
    third_party/fuse-libretro/fuse/peripherals/disk/wd_fdc.c \
    third_party/fuse-libretro/fuse/peripherals/disk/didaktik.c \
    third_party/fuse-libretro/fuse/peripherals/disk/trdos.c \
    third_party/fuse-libretro/fuse/peripherals/flash/am29f010.c \
    third_party/fuse-libretro/fuse/peripherals/ide/divide.c \
    third_party/fuse-libretro/fuse/peripherals/ide/ide.c \
    third_party/fuse-libretro/fuse/peripherals/ide/simpleide.c \
    third_party/fuse-libretro/fuse/peripherals/ide/zxatasp.c \
    third_party/fuse-libretro/fuse/peripherals/ide/zxcf.c \
    third_party/fuse-libretro/fuse/peripherals/ide/divmmc.c \
    third_party/fuse-libretro/fuse/peripherals/ide/divxxx.c \
    third_party/fuse-libretro/fuse/peripherals/ide/zxmmc.c \
    third_party/fuse-libretro/fuse/peripherals/ay.c \
    third_party/fuse-libretro/fuse/peripherals/dck.c \
    third_party/fuse-libretro/fuse/peripherals/fuller.c \
    third_party/fuse-libretro/fuse/peripherals/if1.c \
    third_party/fuse-libretro/fuse/peripherals/if2.c \
    third_party/fuse-libretro/fuse/peripherals/joystick.c \
    third_party/fuse-libretro/fuse/peripherals/kempmouse.c \
    third_party/fuse-libretro/fuse/peripherals/melodik.c \
    third_party/fuse-libretro/fuse/peripherals/printer.c \
    third_party/fuse-libretro/fuse/peripherals/scld.c \
    third_party/fuse-libretro/fuse/peripherals/speccyboot.c \
    third_party/fuse-libretro/fuse/peripherals/specdrum.c \
    third_party/fuse-libretro/fuse/peripherals/spectranet.c \
    third_party/fuse-libretro/fuse/peripherals/ula.c \
    third_party/fuse-libretro/fuse/peripherals/multiface.c \
    third_party/fuse-libretro/fuse/peripherals/ttx2000s.c \
    third_party/fuse-libretro/fuse/peripherals/usource.c \
    third_party/fuse-libretro/fuse/peripherals/covox.c \
    third_party/fuse-libretro/fuse/peripherals/sound/sp0256.c \
    third_party/fuse-libretro/fuse/peripherals/sound/uspeech.c \
    third_party/fuse-libretro/fuse/pokefinder/pokefinder.c \
    third_party/fuse-libretro/fuse/pokefinder/pokemem.c \
    third_party/fuse-libretro/fuse/sound/blipbuffer.c \
    third_party/fuse-libretro/fuse/timer/timer.c \
    third_party/fuse-libretro/fuse/timer/native.c \
    third_party/fuse-libretro/fuse/unittests/unittests.c \
    third_party/fuse-libretro/fuse/z80/z80.c \
    third_party/fuse-libretro/fuse/z80/z80_ops.c \
    third_party/fuse-libretro/fuse/z80/z80_debugger_variables.c \
    third_party/fuse-libretro/fuse/display.c \
    third_party/fuse-libretro/fuse/event.c \
    third_party/fuse-libretro/src/fuse/fuse.c \
    third_party/fuse-libretro/fuse/input.c \
    third_party/fuse-libretro/fuse/keyboard.c \
    third_party/fuse-libretro/fuse/loader.c \
    third_party/fuse-libretro/fuse/machine.c \
    third_party/fuse-libretro/fuse/memory_pages.c \
    third_party/fuse-libretro/fuse/mempool.c \
    third_party/fuse-libretro/fuse/module.c \
    third_party/fuse-libretro/fuse/periph.c \
    third_party/fuse-libretro/fuse/psg.c \
    third_party/fuse-libretro/fuse/rectangle.c \
    third_party/fuse-libretro/fuse/rzx.c \
    third_party/fuse-libretro/src/fuse/settings.c \
    third_party/fuse-libretro/src/fuse/options_enumerate.c \
    third_party/fuse-libretro/fuse/slt.c \
    third_party/fuse-libretro/src/fuse/snapshot.c \
    third_party/fuse-libretro/fuse/sound.c \
    third_party/fuse-libretro/fuse/spectrum.c \
    third_party/fuse-libretro/fuse/tape.c \
    third_party/fuse-libretro/src/fuse/ui.c \
    third_party/fuse-libretro/fuse/uidisplay.c \
    third_party/fuse-libretro/src/fuse/utils.c \
    third_party/fuse-libretro/fuse/phantom_typist.c \
    third_party/fuse-libretro/fuse/uimedia.c \
    third_party/fuse-libretro/fuse/svg.c \
    third_party/fuse-libretro/libspectrum/buffer.c \
    third_party/fuse-libretro/libspectrum/bzip2.c \
    third_party/fuse-libretro/libspectrum/creator.c \
    third_party/fuse-libretro/libspectrum/crypto.c \
    third_party/fuse-libretro/libspectrum/csw.c \
    third_party/fuse-libretro/libspectrum/dck.c \
    third_party/fuse-libretro/libspectrum/ide.c \
    third_party/fuse-libretro/libspectrum/libspectrum.c \
    third_party/fuse-libretro/libspectrum/memory.c \
    third_party/fuse-libretro/libspectrum/microdrive.c \
    third_party/fuse-libretro/libspectrum/myglib/garray.c \
    third_party/fuse-libretro/libspectrum/myglib/ghash.c \
    third_party/fuse-libretro/libspectrum/myglib/gslist.c \
    third_party/fuse-libretro/libspectrum/plusd.c \
    third_party/fuse-libretro/libspectrum/pzx_read.c \
    third_party/fuse-libretro/libspectrum/rzx.c \
    third_party/fuse-libretro/libspectrum/sna.c \
    third_party/fuse-libretro/libspectrum/snapshot.c \
    third_party/fuse-libretro/libspectrum/snap_accessors.c \
    third_party/fuse-libretro/libspectrum/snp.c \
    third_party/fuse-libretro/libspectrum/sp.c \
    third_party/fuse-libretro/libspectrum/symbol_table.c \
    third_party/fuse-libretro/libspectrum/szx.c \
    third_party/fuse-libretro/libspectrum/tap.c \
    third_party/fuse-libretro/libspectrum/tape.c \
    third_party/fuse-libretro/libspectrum/tape_accessors.c \
    third_party/fuse-libretro/libspectrum/tape_block.c \
    third_party/fuse-libretro/libspectrum/tape_set.c \
    third_party/fuse-libretro/libspectrum/timings.c \
    third_party/fuse-libretro/libspectrum/tzx_read.c \
    third_party/fuse-libretro/libspectrum/tzx_write.c \
    third_party/fuse-libretro/libspectrum/utilities.c \
    third_party/fuse-libretro/libspectrum/warajevo_read.c \
    third_party/fuse-libretro/libspectrum/wav.c \
    third_party/fuse-libretro/libspectrum/z80.c \
    third_party/fuse-libretro/libspectrum/z80em.c \
    third_party/fuse-libretro/libspectrum/zlib.c \
    third_party/fuse-libretro/libspectrum/zxs.c \
    third_party/fuse-libretro/libspectrum/mmc.c \
    third_party/fuse-libretro/libspectrum/zip.c \
    third_party/fuse-libretro/zlib/adler32.c \
    third_party/fuse-libretro/zlib/compress.c \
    third_party/fuse-libretro/zlib/crc32.c \
    third_party/fuse-libretro/zlib/deflate.c \
    third_party/fuse-libretro/zlib/gzclose.c \
    third_party/fuse-libretro/zlib/gzlib.c \
    third_party/fuse-libretro/zlib/gzread.c \
    third_party/fuse-libretro/zlib/gzwrite.c \
    third_party/fuse-libretro/zlib/infback.c \
    third_party/fuse-libretro/zlib/inffast.c \
    third_party/fuse-libretro/zlib/inflate.c \
    third_party/fuse-libretro/zlib/inftrees.c \
    third_party/fuse-libretro/zlib/trees.c \
    third_party/fuse-libretro/zlib/uncompr.c \
    third_party/fuse-libretro/zlib/zutil.c \
    third_party/fuse-libretro/bzip2/blocksort.c \
    third_party/fuse-libretro/bzip2/huffman.c \
    third_party/fuse-libretro/bzip2/crctable.c \
    third_party/fuse-libretro/bzip2/randtable.c \
    third_party/fuse-libretro/bzip2/compress.c \
    third_party/fuse-libretro/bzip2/decompress.c \
    third_party/fuse-libretro/bzip2/bzlib.c \
    third_party/fuse-libretro/deps/libretro-common/streams/file_stream.c \
    third_party/fuse-libretro/deps/libretro-common/vfs/vfs_implementation.c \
    third_party/fuse-libretro/deps/libretro-common/file/file_path.c \
    third_party/fuse-libretro/deps/libretro-common/file/file_path_io.c \
    third_party/fuse-libretro/deps/libretro-common/string/stdstring.c \
    third_party/fuse-libretro/deps/libretro-common/lists/string_list.c \
    third_party/fuse-libretro/deps/libretro-common/encodings/encoding_utf.c \
    third_party/fuse-libretro/deps/libretro-common/time/rtime.c \
    third_party/fuse-libretro/deps/libretro-common/compat/compat_strl.c \
    third_party/fuse-libretro/deps/libretro-common/compat/compat_posix_string.c \
    third_party/fuse-libretro/deps/libretro-common/compat/compat_strcasestr.c \
    third_party/fuse-libretro/deps/libretro-common/compat/fopen_utf8.c

fuse_DEFINES := \
    -DHAVE_CONFIG_H

fuse_INCLUDES := \
    -Ithird_party/fuse-libretro/deps/libretro-common/include \
    -Ithird_party/fuse-libretro \
    -Ithird_party/fuse-libretro/src \
    -Ithird_party/fuse-libretro/src/compat \
    -Ithird_party/fuse-libretro/fuse \
    -Ithird_party/fuse-libretro/fuse/compat \
    -Ithird_party/fuse-libretro/libspectrum \
    -Ithird_party/fuse-libretro/zlib \
    -Ithird_party/fuse-libretro/bzip2

