# SPDX-License-Identifier: Zlib
#
# Generated from third_party/vice-libretro/Makefile by scripts/gen-core-mk.py.
# Edit the generator, not this file, then re-run it.

vice_x64_DIR := third_party/vice-libretro
vice_x64_EXTS := crt d64 prg tap

vice_x64_SRCS := \
    third_party/vice-libretro/libretro/libretro-core.c \
    third_party/vice-libretro/libretro/libretro-mapper.c \
    third_party/vice-libretro/libretro/libretro-dc.c \
    third_party/vice-libretro/libretro/libretro-glue.c \
    third_party/vice-libretro/libretro/libretro-vkbd.c \
    third_party/vice-libretro/libretro/libretro-graph.c \
    third_party/vice-libretro/deps/libz/unzip.c \
    third_party/vice-libretro/deps/libz/ioapi.c \
    third_party/vice-libretro/vice/src/alarm.c \
    third_party/vice-libretro/vice/src/attach.c \
    third_party/vice-libretro/vice/src/autostart-prg.c \
    third_party/vice-libretro/vice/src/autostart.c \
    third_party/vice-libretro/vice/src/cbmdos.c \
    third_party/vice-libretro/vice/src/cbmimage.c \
    third_party/vice-libretro/vice/src/charset.c \
    third_party/vice-libretro/vice/src/clipboard.c \
    third_party/vice-libretro/vice/src/cmdline.c \
    third_party/vice-libretro/vice/src/color.c \
    third_party/vice-libretro/vice/src/core/ata.c \
    third_party/vice-libretro/vice/src/core/ciacore.c \
    third_party/vice-libretro/vice/src/core/ciatimer.c \
    third_party/vice-libretro/vice/src/core/cs8900.c \
    third_party/vice-libretro/vice/src/core/flash040core.c \
    third_party/vice-libretro/vice/src/core/flash800core.c \
    third_party/vice-libretro/vice/src/core/fmopl.c \
    third_party/vice-libretro/vice/src/core/i8255a.c \
    third_party/vice-libretro/vice/src/core/m93c86.c \
    third_party/vice-libretro/vice/src/core/mc6821core.c \
    third_party/vice-libretro/vice/src/core/riotcore.c \
    third_party/vice-libretro/vice/src/core/scsi.c \
    third_party/vice-libretro/vice/src/core/ser-eeprom.c \
    third_party/vice-libretro/vice/src/core/spi-flash.c \
    third_party/vice-libretro/vice/src/core/spi-sdcard.c \
    third_party/vice-libretro/vice/src/core/t6721.c \
    third_party/vice-libretro/vice/src/core/tpicore.c \
    third_party/vice-libretro/vice/src/core/viacore.c \
    third_party/vice-libretro/vice/src/core/rtc/bq4830y.c \
    third_party/vice-libretro/vice/src/core/rtc/ds12c887.c \
    third_party/vice-libretro/vice/src/core/rtc/ds1202_1302.c \
    third_party/vice-libretro/vice/src/core/rtc/ds1216e.c \
    third_party/vice-libretro/vice/src/core/rtc/ds1307.c \
    third_party/vice-libretro/vice/src/core/rtc/ds1602.c \
    third_party/vice-libretro/vice/src/core/rtc/pcf8583.c \
    third_party/vice-libretro/vice/src/core/rtc/rtc-58321a.c \
    third_party/vice-libretro/vice/src/core/rtc/rtc-72421.c \
    third_party/vice-libretro/vice/src/core/rtc/rtc.c \
    third_party/vice-libretro/vice/src/crc32.c \
    third_party/vice-libretro/vice/src/crt.c \
    third_party/vice-libretro/vice/src/debug.c \
    third_party/vice-libretro/vice/src/diskimage/diskimage.c \
    third_party/vice-libretro/vice/src/diskimage/fsimage-check.c \
    third_party/vice-libretro/vice/src/diskimage/fsimage-create.c \
    third_party/vice-libretro/vice/src/diskimage/fsimage-dxx.c \
    third_party/vice-libretro/vice/src/diskimage/fsimage-gcr.c \
    third_party/vice-libretro/vice/src/diskimage/fsimage-p64.c \
    third_party/vice-libretro/vice/src/diskimage/fsimage-probe.c \
    third_party/vice-libretro/vice/src/diskimage/fsimage.c \
    third_party/vice-libretro/vice/src/diskimage/realimage.c \
    third_party/vice-libretro/vice/src/drive/ieee/fdc.c \
    third_party/vice-libretro/vice/src/drive/ieee/ieee-cmdline-options.c \
    third_party/vice-libretro/vice/src/drive/ieee/ieee-resources.c \
    third_party/vice-libretro/vice/src/drive/ieee/ieee.c \
    third_party/vice-libretro/vice/src/drive/ieee/ieeerom.c \
    third_party/vice-libretro/vice/src/drive/ieee/memieee.c \
    third_party/vice-libretro/vice/src/drive/ieee/riot1d.c \
    third_party/vice-libretro/vice/src/drive/ieee/riot2d.c \
    third_party/vice-libretro/vice/src/drive/ieee/via1d2031.c \
    third_party/vice-libretro/vice/src/drive/rotation.c \
    third_party/vice-libretro/vice/src/drive/tcbm/glue1551.c \
    third_party/vice-libretro/vice/src/drive/tcbm/mem1551.c \
    third_party/vice-libretro/vice/src/drive/tcbm/tcbm-cmdline-options.c \
    third_party/vice-libretro/vice/src/drive/tcbm/tcbm-resources.c \
    third_party/vice-libretro/vice/src/drive/tcbm/tcbm.c \
    third_party/vice-libretro/vice/src/drive/tcbm/tcbmrom.c \
    third_party/vice-libretro/vice/src/drive/tcbm/tpid.c \
    third_party/vice-libretro/vice/src/dma.c \
    third_party/vice-libretro/vice/src/event.c \
    third_party/vice-libretro/vice/src/fileio/cbmfile.c \
    third_party/vice-libretro/vice/src/fileio/fileio.c \
    third_party/vice-libretro/vice/src/fileio/p00.c \
    third_party/vice-libretro/vice/src/findpath.c \
    third_party/vice-libretro/vice/src/fliplist.c \
    third_party/vice-libretro/vice/src/fsdevice/fsdevice-close.c \
    third_party/vice-libretro/vice/src/fsdevice/fsdevice-cmdline-options.c \
    third_party/vice-libretro/vice/src/fsdevice/fsdevice-filename.c \
    third_party/vice-libretro/vice/src/fsdevice/fsdevice-flush.c \
    third_party/vice-libretro/vice/src/fsdevice/fsdevice-open.c \
    third_party/vice-libretro/vice/src/fsdevice/fsdevice-read.c \
    third_party/vice-libretro/vice/src/fsdevice/fsdevice-resources.c \
    third_party/vice-libretro/vice/src/fsdevice/fsdevice-write.c \
    third_party/vice-libretro/vice/src/fsdevice/fsdevice.c \
    third_party/vice-libretro/vice/src/gcr.c \
    third_party/vice-libretro/vice/src/iecbus/iecbus.c \
    third_party/vice-libretro/vice/src/imagecontents/diskcontents-block.c \
    third_party/vice-libretro/vice/src/imagecontents/diskcontents-iec.c \
    third_party/vice-libretro/vice/src/imagecontents/diskcontents.c \
    third_party/vice-libretro/vice/src/imagecontents/imagecontents.c \
    third_party/vice-libretro/vice/src/imagecontents/tapecontents.c \
    third_party/vice-libretro/vice/src/init.c \
    third_party/vice-libretro/vice/src/initcmdline.c \
    third_party/vice-libretro/vice/src/interrupt.c \
    third_party/vice-libretro/vice/src/kbdbuf.c \
    third_party/vice-libretro/vice/src/keyboard.c \
    third_party/vice-libretro/vice/src/keymap.c \
    third_party/vice-libretro/vice/src/lib.c \
    third_party/vice-libretro/vice/src/lib/p64/p64.c \
    third_party/vice-libretro/vice/src/log.c \
    third_party/vice-libretro/vice/src/machine-bus.c \
    third_party/vice-libretro/vice/src/machine.c \
    third_party/vice-libretro/vice/src/main.c \
    third_party/vice-libretro/vice/src/midi.c \
    third_party/vice-libretro/vice/src/network.c \
    third_party/vice-libretro/vice/src/opencbmlib.c \
    third_party/vice-libretro/vice/src/palette.c \
    third_party/vice-libretro/vice/src/parallel/parallel-trap.c \
    third_party/vice-libretro/vice/src/parallel/parallel.c \
    third_party/vice-libretro/vice/src/profiler.c \
    third_party/vice-libretro/vice/src/ram.c \
    third_party/vice-libretro/vice/src/raster/raster-cache.c \
    third_party/vice-libretro/vice/src/raster/raster-canvas.c \
    third_party/vice-libretro/vice/src/raster/raster-changes.c \
    third_party/vice-libretro/vice/src/raster/raster-cmdline-options.c \
    third_party/vice-libretro/vice/src/raster/raster-line-changes-sprite.c \
    third_party/vice-libretro/vice/src/raster/raster-line-changes.c \
    third_party/vice-libretro/vice/src/raster/raster-line.c \
    third_party/vice-libretro/vice/src/raster/raster-modes.c \
    third_party/vice-libretro/vice/src/raster/raster-resources.c \
    third_party/vice-libretro/vice/src/raster/raster-snapshot.c \
    third_party/vice-libretro/vice/src/raster/raster-sprite-cache.c \
    third_party/vice-libretro/vice/src/raster/raster-sprite-status.c \
    third_party/vice-libretro/vice/src/raster/raster-sprite.c \
    third_party/vice-libretro/vice/src/raster/raster.c \
    third_party/vice-libretro/vice/src/rawfile.c \
    third_party/vice-libretro/vice/src/rawnet.c \
    third_party/vice-libretro/vice/src/resources.c \
    third_party/vice-libretro/vice/src/romset.c \
    third_party/vice-libretro/vice/src/rs232drv/rs232.c \
    third_party/vice-libretro/vice/src/rs232drv/rs232drv.c \
    third_party/vice-libretro/vice/src/rs232drv/rs232net.c \
    third_party/vice-libretro/vice/src/rs232drv/rsuser.c \
    third_party/vice-libretro/vice/src/screenshot.c \
    third_party/vice-libretro/vice/src/snapshot.c \
    third_party/vice-libretro/vice/src/socket.c \
    third_party/vice-libretro/vice/src/sound.c \
    third_party/vice-libretro/vice/src/sysfile.c \
    third_party/vice-libretro/vice/src/traps.c \
    third_party/vice-libretro/vice/src/util.c \
    third_party/vice-libretro/vice/src/vicefeatures.c \
    third_party/vice-libretro/vice/src/vdrive/vdrive-bam.c \
    third_party/vice-libretro/vice/src/vdrive/vdrive-command.c \
    third_party/vice-libretro/vice/src/vdrive/vdrive-dir.c \
    third_party/vice-libretro/vice/src/vdrive/vdrive-iec.c \
    third_party/vice-libretro/vice/src/vdrive/vdrive-internal.c \
    third_party/vice-libretro/vice/src/vdrive/vdrive-rel.c \
    third_party/vice-libretro/vice/src/vdrive/vdrive-snapshot.c \
    third_party/vice-libretro/vice/src/vdrive/vdrive.c \
    third_party/vice-libretro/vice/src/video/render1x1.c \
    third_party/vice-libretro/vice/src/video/render1x1ntsc.c \
    third_party/vice-libretro/vice/src/video/render1x1pal.c \
    third_party/vice-libretro/vice/src/video/render1x1rgbi.c \
    third_party/vice-libretro/vice/src/video/video-canvas.c \
    third_party/vice-libretro/vice/src/video/video-cmdline-options.c \
    third_party/vice-libretro/vice/src/video/video-color.c \
    third_party/vice-libretro/vice/src/video/video-render.c \
    third_party/vice-libretro/vice/src/video/video-render-crtmono.c \
    third_party/vice-libretro/vice/src/video/video-render-palntsc.c \
    third_party/vice-libretro/vice/src/video/video-render-rgbi.c \
    third_party/vice-libretro/vice/src/video/video-resources.c \
    third_party/vice-libretro/vice/src/video/video-sound.c \
    third_party/vice-libretro/vice/src/video/video-viewport.c \
    third_party/vice-libretro/vice/src/vsync.c \
    third_party/vice-libretro/vice/src/zfile.c \
    third_party/vice-libretro/vice/src/zipcode.c \
    third_party/vice-libretro/vice/src/c64/c64-cmdline-options.c \
    third_party/vice-libretro/vice/src/c64/c64-memory-hacks.c \
    third_party/vice-libretro/vice/src/c64/c64-resources.c \
    third_party/vice-libretro/vice/src/c64/c64.c \
    third_party/vice-libretro/vice/src/c64/c64bus.c \
    third_party/vice-libretro/vice/src/c64/c64cia1.c \
    third_party/vice-libretro/vice/src/c64/c64cia2.c \
    third_party/vice-libretro/vice/src/c64/c64cpu.c \
    third_party/vice-libretro/vice/src/c64/c64datasette.c \
    third_party/vice-libretro/vice/src/c64/c64drive.c \
    third_party/vice-libretro/vice/src/c64/c64export.c \
    third_party/vice-libretro/vice/src/c64/c64fastiec.c \
    third_party/vice-libretro/vice/src/c64/c64gluelogic.c \
    third_party/vice-libretro/vice/src/c64/c64iec.c \
    third_party/vice-libretro/vice/src/c64/c64io.c \
    third_party/vice-libretro/vice/src/c64/c64keyboard.c \
    third_party/vice-libretro/vice/src/c64/c64mem.c \
    third_party/vice-libretro/vice/src/c64/c64meminit.c \
    third_party/vice-libretro/vice/src/c64/c64memlimit.c \
    third_party/vice-libretro/vice/src/c64/c64memrom.c \
    third_party/vice-libretro/vice/src/c64/c64memsnapshot.c \
    third_party/vice-libretro/vice/src/c64/c64model.c \
    third_party/vice-libretro/vice/src/c64/c64parallel.c \
    third_party/vice-libretro/vice/src/c64/c64pla.c \
    third_party/vice-libretro/vice/src/c64/c64printer.c \
    third_party/vice-libretro/vice/src/c64/c64rom.c \
    third_party/vice-libretro/vice/src/c64/c64romset.c \
    third_party/vice-libretro/vice/src/c64/c64rsuser.c \
    third_party/vice-libretro/vice/src/c64/c64sound.c \
    third_party/vice-libretro/vice/src/c64/c64video.c \
    third_party/vice-libretro/vice/src/c64/c64_256k.c \
    third_party/vice-libretro/vice/src/c64/plus60k.c \
    third_party/vice-libretro/vice/src/c64/plus256k.c \
    third_party/vice-libretro/vice/src/c64/reloc65.c \
    third_party/vice-libretro/vice/src/c64/cart/actionreplay.c \
    third_party/vice-libretro/vice/src/c64/cart/actionreplay2.c \
    third_party/vice-libretro/vice/src/c64/cart/actionreplay3.c \
    third_party/vice-libretro/vice/src/c64/cart/actionreplay4.c \
    third_party/vice-libretro/vice/src/c64/cart/atomicpower.c \
    third_party/vice-libretro/vice/src/c64/cart/bisplus.c \
    third_party/vice-libretro/vice/src/c64/cart/blackbox3.c \
    third_party/vice-libretro/vice/src/c64/cart/blackbox4.c \
    third_party/vice-libretro/vice/src/c64/cart/blackbox8.c \
    third_party/vice-libretro/vice/src/c64/cart/blackbox9.c \
    third_party/vice-libretro/vice/src/c64/cart/bmpdataturbo.c \
    third_party/vice-libretro/vice/src/c64/cart/c64-generic.c \
    third_party/vice-libretro/vice/src/c64/cart/c64-midi.c \
    third_party/vice-libretro/vice/src/c64/cart/c64acia1.c \
    third_party/vice-libretro/vice/src/c64/cart/c64cart.c \
    third_party/vice-libretro/vice/src/c64/cart/c64carthooks.c \
    third_party/vice-libretro/vice/src/c64/cart/c64cartmem.c \
    third_party/vice-libretro/vice/src/c64/cart/c64tpi.c \
    third_party/vice-libretro/vice/src/c64/cart/capture.c \
    third_party/vice-libretro/vice/src/c64/cart/clockport-mp3at64.c \
    third_party/vice-libretro/vice/src/c64/cart/clockport-rrnet.c \
    third_party/vice-libretro/vice/src/c64/cart/clockport.c \
    third_party/vice-libretro/vice/src/c64/cart/comal80.c \
    third_party/vice-libretro/vice/src/c64/cart/cs8900io.c \
    third_party/vice-libretro/vice/src/c64/cart/daa.c \
    third_party/vice-libretro/vice/src/c64/cart/debugcart.c \
    third_party/vice-libretro/vice/src/c64/cart/delaep7x8.c \
    third_party/vice-libretro/vice/src/c64/cart/delaep64.c \
    third_party/vice-libretro/vice/src/c64/cart/delaep256.c \
    third_party/vice-libretro/vice/src/c64/cart/diashowmaker.c \
    third_party/vice-libretro/vice/src/c64/cart/digimax.c \
    third_party/vice-libretro/vice/src/c64/cart/dinamic.c \
    third_party/vice-libretro/vice/src/c64/cart/drean.c \
    third_party/vice-libretro/vice/src/c64/cart/dqbb.c \
    third_party/vice-libretro/vice/src/c64/cart/ds12c887rtc.c \
    third_party/vice-libretro/vice/src/c64/cart/easycalc.c \
    third_party/vice-libretro/vice/src/c64/cart/easyflash.c \
    third_party/vice-libretro/vice/src/c64/cart/epyxfastload.c \
    third_party/vice-libretro/vice/src/c64/cart/ethernetcart.c \
    third_party/vice-libretro/vice/src/c64/cart/exos.c \
    third_party/vice-libretro/vice/src/c64/cart/expert.c \
    third_party/vice-libretro/vice/src/c64/cart/final.c \
    third_party/vice-libretro/vice/src/c64/cart/final3.c \
    third_party/vice-libretro/vice/src/c64/cart/finalplus.c \
    third_party/vice-libretro/vice/src/c64/cart/formel64.c \
    third_party/vice-libretro/vice/src/c64/cart/freezeframe.c \
    third_party/vice-libretro/vice/src/c64/cart/freezeframe2.c \
    third_party/vice-libretro/vice/src/c64/cart/freezemachine.c \
    third_party/vice-libretro/vice/src/c64/cart/funplay.c \
    third_party/vice-libretro/vice/src/c64/cart/gamekiller.c \
    third_party/vice-libretro/vice/src/c64/cart/georam.c \
    third_party/vice-libretro/vice/src/c64/cart/gmod2.c \
    third_party/vice-libretro/vice/src/c64/cart/gmod3.c \
    third_party/vice-libretro/vice/src/c64/cart/gs.c \
    third_party/vice-libretro/vice/src/c64/cart/hyperbasic.c \
    third_party/vice-libretro/vice/src/c64/cart/ide64.c \
    third_party/vice-libretro/vice/src/c64/cart/ieeeflash64.c \
    third_party/vice-libretro/vice/src/c64/cart/isepic.c \
    third_party/vice-libretro/vice/src/c64/cart/kcs.c \
    third_party/vice-libretro/vice/src/c64/cart/kingsoft.c \
    third_party/vice-libretro/vice/src/c64/cart/ltkernal.c \
    third_party/vice-libretro/vice/src/c64/cart/mach5.c \
    third_party/vice-libretro/vice/src/c64/cart/magicdesk.c \
    third_party/vice-libretro/vice/src/c64/cart/magicdesk16.c \
    third_party/vice-libretro/vice/src/c64/cart/magicformel.c \
    third_party/vice-libretro/vice/src/c64/cart/magicvoice.c \
    third_party/vice-libretro/vice/src/c64/cart/maxbasic.c \
    third_party/vice-libretro/vice/src/c64/cart/megabyter.c \
    third_party/vice-libretro/vice/src/c64/cart/mikroass.c \
    third_party/vice-libretro/vice/src/c64/cart/multimax.c \
    third_party/vice-libretro/vice/src/c64/cart/mmc64.c \
    third_party/vice-libretro/vice/src/c64/cart/mmcreplay.c \
    third_party/vice-libretro/vice/src/c64/cart/ocean.c \
    third_party/vice-libretro/vice/src/c64/cart/pagefox.c \
    third_party/vice-libretro/vice/src/c64/cart/partner64.c \
    third_party/vice-libretro/vice/src/c64/cart/profidos.c \
    third_party/vice-libretro/vice/src/c64/cart/prophet64.c \
    third_party/vice-libretro/vice/src/c64/cart/ramcart.c \
    third_party/vice-libretro/vice/src/c64/cart/ramlink.c \
    third_party/vice-libretro/vice/src/c64/cart/retroreplay.c \
    third_party/vice-libretro/vice/src/c64/cart/reu.c \
    third_party/vice-libretro/vice/src/c64/cart/rexep256.c \
    third_party/vice-libretro/vice/src/c64/cart/rexutility.c \
    third_party/vice-libretro/vice/src/c64/cart/rgcd.c \
    third_party/vice-libretro/vice/src/c64/cart/ross.c \
    third_party/vice-libretro/vice/src/c64/cart/rrnetmk3.c \
    third_party/vice-libretro/vice/src/c64/cart/sdbox.c \
    third_party/vice-libretro/vice/src/c64/cart/sfx_soundexpander.c \
    third_party/vice-libretro/vice/src/c64/cart/sfx_soundsampler.c \
    third_party/vice-libretro/vice/src/c64/cart/shortbus.c \
    third_party/vice-libretro/vice/src/c64/cart/shortbus_digimax.c \
    third_party/vice-libretro/vice/src/c64/cart/shortbus_etfe.c \
    third_party/vice-libretro/vice/src/c64/cart/silverrock128.c \
    third_party/vice-libretro/vice/src/c64/cart/simonsbasic.c \
    third_party/vice-libretro/vice/src/c64/cart/snapshot64.c \
    third_party/vice-libretro/vice/src/c64/cart/stardos.c \
    third_party/vice-libretro/vice/src/c64/cart/stb.c \
    third_party/vice-libretro/vice/src/c64/cart/superexplode5.c \
    third_party/vice-libretro/vice/src/c64/cart/supergames.c \
    third_party/vice-libretro/vice/src/c64/cart/supersnapshot.c \
    third_party/vice-libretro/vice/src/c64/cart/supersnapshot4.c \
    third_party/vice-libretro/vice/src/c64/cart/turtlegraphics.c \
    third_party/vice-libretro/vice/src/c64/cart/uc1.c \
    third_party/vice-libretro/vice/src/c64/cart/uc2.c \
    third_party/vice-libretro/vice/src/c64/cart/rexramfloppy.c \
    third_party/vice-libretro/vice/src/c64/cart/warpspeed.c \
    third_party/vice-libretro/vice/src/c64/cart/westermann.c \
    third_party/vice-libretro/vice/src/c64/cart/zaxxon.c \
    third_party/vice-libretro/vice/src/c64/cart/zippcode48.c \
    third_party/vice-libretro/vice/src/datasette/datasette.c \
    third_party/vice-libretro/vice/src/datasette/datasette-sound.c \
    third_party/vice-libretro/vice/src/diag/c64_diag_586220_harness.c \
    third_party/vice-libretro/vice/src/drive/drive-check.c \
    third_party/vice-libretro/vice/src/drive/drive-cmdline-options.c \
    third_party/vice-libretro/vice/src/drive/drive-resources.c \
    third_party/vice-libretro/vice/src/drive/drive-snapshot.c \
    third_party/vice-libretro/vice/src/drive/drive-sound.c \
    third_party/vice-libretro/vice/src/drive/drive-writeprotect.c \
    third_party/vice-libretro/vice/src/drive/drive.c \
    third_party/vice-libretro/vice/src/drive/drivecpu.c \
    third_party/vice-libretro/vice/src/drive/drivecpu65c02.c \
    third_party/vice-libretro/vice/src/drive/driveimage.c \
    third_party/vice-libretro/vice/src/drive/drivemem.c \
    third_party/vice-libretro/vice/src/drive/driverom.c \
    third_party/vice-libretro/vice/src/drive/drivesync.c \
    third_party/vice-libretro/vice/src/drive/iec/c64exp/c64exp-cmdline-options.c \
    third_party/vice-libretro/vice/src/drive/iec/c64exp/c64exp-resources.c \
    third_party/vice-libretro/vice/src/drive/iec/c64exp/dolphindos3.c \
    third_party/vice-libretro/vice/src/drive/iec/c64exp/iec-c64exp.c \
    third_party/vice-libretro/vice/src/drive/iec/c64exp/profdos.c \
    third_party/vice-libretro/vice/src/drive/iec/c64exp/supercard.c \
    third_party/vice-libretro/vice/src/drive/iec/c64exp/stardos-exp.c \
    third_party/vice-libretro/vice/src/drive/iec/cia1571d.c \
    third_party/vice-libretro/vice/src/drive/iec/cia1581d.c \
    third_party/vice-libretro/vice/src/drive/iec/cmdhd.c \
    third_party/vice-libretro/vice/src/drive/iec/fdd.c \
    third_party/vice-libretro/vice/src/drive/iec/glue1571.c \
    third_party/vice-libretro/vice/src/drive/iec/iec-cmdline-options.c \
    third_party/vice-libretro/vice/src/drive/iec/iec-resources.c \
    third_party/vice-libretro/vice/src/drive/iec/iec.c \
    third_party/vice-libretro/vice/src/drive/iec/iecrom.c \
    third_party/vice-libretro/vice/src/drive/iec/memiec.c \
    third_party/vice-libretro/vice/src/drive/iec/pc8477.c \
    third_party/vice-libretro/vice/src/drive/iec/via1d1541.c \
    third_party/vice-libretro/vice/src/drive/iec/via4000.c \
    third_party/vice-libretro/vice/src/drive/iec/wd1770.c \
    third_party/vice-libretro/vice/src/drive/iecieee/iecieee.c \
    third_party/vice-libretro/vice/src/drive/iecieee/via2d.c \
    third_party/vice-libretro/vice/src/joyport/bbrtc.c \
    third_party/vice-libretro/vice/src/joyport/cardkey.c \
    third_party/vice-libretro/vice/src/joyport/coplin_keypad.c \
    third_party/vice-libretro/vice/src/joyport/cx21.c \
    third_party/vice-libretro/vice/src/joyport/cx85.c \
    third_party/vice-libretro/vice/src/joyport/inception.c \
    third_party/vice-libretro/vice/src/joyport/joyport.c \
    third_party/vice-libretro/vice/src/joyport/joyport_io_sim.c \
    third_party/vice-libretro/vice/src/joyport/joystick.c \
    third_party/vice-libretro/vice/src/joyport/lightpen.c \
    third_party/vice-libretro/vice/src/joyport/mouse.c \
    third_party/vice-libretro/vice/src/joyport/mouse_1351.c \
    third_party/vice-libretro/vice/src/joyport/mouse_neos.c \
    third_party/vice-libretro/vice/src/joyport/mouse_paddle.c \
    third_party/vice-libretro/vice/src/joyport/mouse_quadrature.c \
    third_party/vice-libretro/vice/src/joyport/multijoy.c \
    third_party/vice-libretro/vice/src/joyport/ninja_snespad.c \
    third_party/vice-libretro/vice/src/joyport/paperclip2.c \
    third_party/vice-libretro/vice/src/joyport/paperclip64.c \
    third_party/vice-libretro/vice/src/joyport/paperclip64e.c \
    third_party/vice-libretro/vice/src/joyport/paperclip64sc.c \
    third_party/vice-libretro/vice/src/joyport/powerpad.c \
    third_party/vice-libretro/vice/src/joyport/protopad.c \
    third_party/vice-libretro/vice/src/joyport/rushware_keypad.c \
    third_party/vice-libretro/vice/src/joyport/sampler2bit.c \
    third_party/vice-libretro/vice/src/joyport/sampler4bit.c \
    third_party/vice-libretro/vice/src/joyport/script64_dongle.c \
    third_party/vice-libretro/vice/src/joyport/spaceballs.c \
    third_party/vice-libretro/vice/src/joyport/trapthem_snespad.c \
    third_party/vice-libretro/vice/src/joyport/vizawrite64_dongle.c \
    third_party/vice-libretro/vice/src/joyport/waasoft_dongle.c \
    third_party/vice-libretro/vice/src/printerdrv/driver-select.c \
    third_party/vice-libretro/vice/src/printerdrv/drv-ascii.c \
    third_party/vice-libretro/vice/src/printerdrv/drv-raw.c \
    third_party/vice-libretro/vice/src/printerdrv/interface-serial.c \
    third_party/vice-libretro/vice/src/printerdrv/interface-userport.c \
    third_party/vice-libretro/vice/src/printerdrv/output-graphics.c \
    third_party/vice-libretro/vice/src/printerdrv/output-select.c \
    third_party/vice-libretro/vice/src/printerdrv/output-text.c \
    third_party/vice-libretro/vice/src/printerdrv/printer-serial.c \
    third_party/vice-libretro/vice/src/printerdrv/printer-userport.c \
    third_party/vice-libretro/vice/src/printerdrv/printer.c \
    third_party/vice-libretro/vice/src/serial/fsdrive.c \
    third_party/vice-libretro/vice/src/serial/iec-ieee488-shared.c \
    third_party/vice-libretro/vice/src/serial/realdevice.c \
    third_party/vice-libretro/vice/src/serial/serial-device.c \
    third_party/vice-libretro/vice/src/serial/serial-iec-bus.c \
    third_party/vice-libretro/vice/src/serial/serial-iec-device.c \
    third_party/vice-libretro/vice/src/serial/serial-iec-lib.c \
    third_party/vice-libretro/vice/src/serial/serial-iec.c \
    third_party/vice-libretro/vice/src/serial/serial-realdevice.c \
    third_party/vice-libretro/vice/src/serial/serial-trap.c \
    third_party/vice-libretro/vice/src/serial/serial.c \
    third_party/vice-libretro/vice/src/sid/catweaselmkiii.c \
    third_party/vice-libretro/vice/src/sid/fastsid.c \
    third_party/vice-libretro/vice/src/sid/hardsid.c \
    third_party/vice-libretro/vice/src/sid/parsid.c \
    third_party/vice-libretro/vice/src/sid/sid-cmdline-options.c \
    third_party/vice-libretro/vice/src/sid/sid-resources.c \
    third_party/vice-libretro/vice/src/sid/sid-snapshot.c \
    third_party/vice-libretro/vice/src/sid/sid.c \
    third_party/vice-libretro/vice/src/sid/ssi2001.c \
    third_party/vice-libretro/vice/src/tape/t64.c \
    third_party/vice-libretro/vice/src/tape/tap.c \
    third_party/vice-libretro/vice/src/tape/tape-internal.c \
    third_party/vice-libretro/vice/src/tape/tape-snapshot.c \
    third_party/vice-libretro/vice/src/tape/tape.c \
    third_party/vice-libretro/vice/src/tape/tapeimage.c \
    third_party/vice-libretro/vice/src/tapeport/cp-clockf83.c \
    third_party/vice-libretro/vice/src/tapeport/dtl-basic-dongle.c \
    third_party/vice-libretro/vice/src/tapeport/sense-dongle.c \
    third_party/vice-libretro/vice/src/tapeport/tapecart.c \
    third_party/vice-libretro/vice/src/tapeport/tapeport.c \
    third_party/vice-libretro/vice/src/tapeport/tape_diag_586220_harness.c \
    third_party/vice-libretro/vice/src/tapeport/wordcraft-dongle.c \
    third_party/vice-libretro/vice/src/userport/userport.c \
    third_party/vice-libretro/vice/src/userport/userport_4bit_sampler.c \
    third_party/vice-libretro/vice/src/userport/userport_8bss.c \
    third_party/vice-libretro/vice/src/userport/userport_dac.c \
    third_party/vice-libretro/vice/src/userport/userport_diag_586220_harness.c \
    third_party/vice-libretro/vice/src/userport/userport_diag_pin.c \
    third_party/vice-libretro/vice/src/userport/userport_digimax.c \
    third_party/vice-libretro/vice/src/userport/userport_hks_joystick.c \
    third_party/vice-libretro/vice/src/userport/userport_hummer_joystick.c \
    third_party/vice-libretro/vice/src/userport/userport_io_sim.c \
    third_party/vice-libretro/vice/src/userport/userport_joystick.c \
    third_party/vice-libretro/vice/src/userport/userport_petscii_snespad.c \
    third_party/vice-libretro/vice/src/userport/userport_ps2mouse.c \
    third_party/vice-libretro/vice/src/userport/userport_rtc_58321a.c \
    third_party/vice-libretro/vice/src/userport/userport_rtc_ds1307.c \
    third_party/vice-libretro/vice/src/userport/userport_spt_joystick.c \
    third_party/vice-libretro/vice/src/userport/userport_superpad64.c \
    third_party/vice-libretro/vice/src/userport/userport_synergy_joystick.c \
    third_party/vice-libretro/vice/src/userport/userport_v8_joystick.c \
    third_party/vice-libretro/vice/src/userport/userport_wic64.c \
    third_party/vice-libretro/vice/src/userport/userport_woj_joystick.c \
    third_party/vice-libretro/vice/src/vicii/vicii-badline.c \
    third_party/vice-libretro/vice/src/vicii/vicii-cmdline-options.c \
    third_party/vice-libretro/vice/src/vicii/vicii-color.c \
    third_party/vice-libretro/vice/src/vicii/vicii-draw.c \
    third_party/vice-libretro/vice/src/vicii/vicii-fetch.c \
    third_party/vice-libretro/vice/src/vicii/vicii-irq.c \
    third_party/vice-libretro/vice/src/vicii/vicii-mem.c \
    third_party/vice-libretro/vice/src/vicii/vicii-phi1.c \
    third_party/vice-libretro/vice/src/vicii/vicii-resources.c \
    third_party/vice-libretro/vice/src/vicii/vicii-snapshot.c \
    third_party/vice-libretro/vice/src/vicii/vicii-sprites.c \
    third_party/vice-libretro/vice/src/vicii/vicii-stubs.c \
    third_party/vice-libretro/vice/src/vicii/vicii-timing.c \
    third_party/vice-libretro/vice/src/vicii/vicii.c \
    third_party/vice-libretro/vice/src/arch/shared/socketdrv/socketdrv.c \
    third_party/vice-libretro/retrodep/embedded.c \
    third_party/vice-libretro/retrodep/embedded/c64embedded.c \
    third_party/vice-libretro/retrodep/info.c \
    third_party/vice-libretro/retrodep/cart/cpmcart.c \
    third_party/vice-libretro/retrodep/gfxoutputdrv/gfxoutput.c \
    third_party/vice-libretro/retrodep/monitor/asm6502.c \
    third_party/vice-libretro/retrodep/monitor/asmR65C02.c \
    third_party/vice-libretro/retrodep/monitor/asmz80.c \
    third_party/vice-libretro/retrodep/monitor/monitor.c \
    third_party/vice-libretro/retrodep/monitor/monitor_network.c \
    third_party/vice-libretro/retrodep/monitor/mon_util.c \
    third_party/vice-libretro/retrodep/printerdrv/drv-1520.c \
    third_party/vice-libretro/retrodep/printerdrv/drv-mps803.c \
    third_party/vice-libretro/retrodep/printerdrv/drv-nl10.c \
    third_party/vice-libretro/retrodep/samplerdrv/file_drv.c \
    third_party/vice-libretro/retrodep/samplerdrv/sampler.c \
    third_party/vice-libretro/retrodep/video/renderscale2x.c \
    third_party/vice-libretro/retrodep/video/video-render-2x2.c \
    third_party/vice-libretro/retrodep/archdep.c \
    third_party/vice-libretro/retrodep/console.c \
    third_party/vice-libretro/retrodep/joy.c \
    third_party/vice-libretro/retrodep/lightpendrv.c \
    third_party/vice-libretro/retrodep/kbd.c \
    third_party/vice-libretro/retrodep/mousedrv.c \
    third_party/vice-libretro/retrodep/signals.c \
    third_party/vice-libretro/retrodep/soundretro.c \
    third_party/vice-libretro/retrodep/ui.c \
    third_party/vice-libretro/retrodep/uimon.c \
    third_party/vice-libretro/retrodep/uistatusbar.c \
    third_party/vice-libretro/retrodep/video.c \
    third_party/vice-libretro/retrodep/vsyncarch.c \
    third_party/vice-libretro/deps/libz/adler32.c \
    third_party/vice-libretro/deps/libz/crc32.c \
    third_party/vice-libretro/deps/libz/deflate.c \
    third_party/vice-libretro/deps/libz/gzclose.c \
    third_party/vice-libretro/deps/libz/gzlib.c \
    third_party/vice-libretro/deps/libz/gzread.c \
    third_party/vice-libretro/deps/libz/gzwrite.c \
    third_party/vice-libretro/deps/libz/inffast.c \
    third_party/vice-libretro/deps/libz/inflate.c \
    third_party/vice-libretro/deps/libz/inftrees.c \
    third_party/vice-libretro/deps/libz/trees.c \
    third_party/vice-libretro/deps/libz/zutil.c \
    third_party/vice-libretro/deps/7zip/7zArcIn.c \
    third_party/vice-libretro/deps/7zip/7zBuf.c \
    third_party/vice-libretro/deps/7zip/7zCrc.c \
    third_party/vice-libretro/deps/7zip/7zCrcOpt.c \
    third_party/vice-libretro/deps/7zip/7zDec.c \
    third_party/vice-libretro/deps/7zip/7zFile.c \
    third_party/vice-libretro/deps/7zip/7zStream.c \
    third_party/vice-libretro/deps/7zip/Bcj2.c \
    third_party/vice-libretro/deps/7zip/Bra.c \
    third_party/vice-libretro/deps/7zip/Bra86.c \
    third_party/vice-libretro/deps/7zip/BraIA64.c \
    third_party/vice-libretro/deps/7zip/CpuArch.c \
    third_party/vice-libretro/deps/7zip/Delta.c \
    third_party/vice-libretro/deps/7zip/Lzma2Dec.c \
    third_party/vice-libretro/deps/7zip/LzmaDec.c \
    third_party/vice-libretro/libretro-common/compat/compat_strl.c \
    third_party/vice-libretro/libretro-common/compat/compat_strcasestr.c \
    third_party/vice-libretro/libretro-common/compat/fopen_utf8.c \
    third_party/vice-libretro/libretro-common/encodings/encoding_utf.c \
    third_party/vice-libretro/libretro-common/file/file_path.c \
    third_party/vice-libretro/libretro-common/file/file_path_io.c \
    third_party/vice-libretro/libretro-common/file/retro_dirent.c \
    third_party/vice-libretro/libretro-common/streams/file_stream.c \
    third_party/vice-libretro/libretro-common/streams/file_stream_transforms.c \
    third_party/vice-libretro/libretro-common/string/stdstring.c \
    third_party/vice-libretro/libretro-common/time/rtime.c \
    third_party/vice-libretro/libretro-common/vfs/vfs_implementation.c

vice_x64_CXX_SRCS := \
    third_party/vice-libretro/vice/src/resid/dac.cc \
    third_party/vice-libretro/vice/src/resid/envelope.cc \
    third_party/vice-libretro/vice/src/resid/extfilt.cc \
    third_party/vice-libretro/vice/src/resid/filter8580new.cc \
    third_party/vice-libretro/vice/src/resid/pot.cc \
    third_party/vice-libretro/vice/src/resid/sid.cc \
    third_party/vice-libretro/vice/src/resid/version.cc \
    third_party/vice-libretro/vice/src/resid/voice.cc \
    third_party/vice-libretro/vice/src/resid/wave.cc \
    third_party/vice-libretro/vice/src/sid/resid.cc \
    third_party/vice-libretro/vice/src/sid/resid-fp.cc \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/version.cc \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/Dac.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/EnvelopeGenerator.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/ExternalFilter.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/Filter.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/Filter6581.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/Filter8580.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/FilterModelConfig.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/FilterModelConfig8580.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/Integrator.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/Integrator8580.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/OpAmp.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/resample/SincResampler.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/SID.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/Spline.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/WaveformCalculator.cpp \
    third_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp/WaveformGenerator.cpp

vice_x64_DEFINES := \
    -DHAVE_7ZIP -DHAVE_CONFIG_H -DNDEBUG -DUSE_LIBRETRO_VFS -D_7ZIP_ST -D__LIBRETRO__ -D__X64__

vice_x64_INCLUDES := \
    -Ithird_party/vice-libretro/vice/src \
    -Ithird_party/vice-libretro \
    -Ithird_party/vice-libretro/libretro \
    -Ithird_party/vice-libretro/include \
    -Ithird_party/vice-libretro/include/embedded \
    -Ithird_party/vice-libretro/vice/src/core/rtc \
    -Ithird_party/vice-libretro/vice/src/lib \
    -Ithird_party/vice-libretro/vice/src/printerdrv \
    -Ithird_party/vice-libretro/retrodep \
    -Ithird_party/vice-libretro/libretro-common/include \
    -Ithird_party/vice-libretro/deps/libz \
    -Ithird_party/vice-libretro/vice/src/sid \
    -Ithird_party/vice-libretro/vice/src/arch/shared \
    -Ithird_party/vice-libretro/vice/src/c64 \
    -Ithird_party/vice-libretro/vice/src/c64/cart \
    -Ithird_party/vice-libretro/vice/src/c64dtv \
    -Ithird_party/vice-libretro/vice/src/core \
    -Ithird_party/vice-libretro/vice/src/datasette \
    -Ithird_party/vice-libretro/vice/src/diag \
    -Ithird_party/vice-libretro/vice/src/drive \
    -Ithird_party/vice-libretro/vice/src/drive/iec \
    -Ithird_party/vice-libretro/vice/src/drive/iec/c64exp \
    -Ithird_party/vice-libretro/vice/src/drive/ieee \
    -Ithird_party/vice-libretro/vice/src/drive/tcbm \
    -Ithird_party/vice-libretro/vice/src/fsdevice \
    -Ithird_party/vice-libretro/vice/src/imagecontents \
    -Ithird_party/vice-libretro/vice/src/joyport \
    -Ithird_party/vice-libretro/vice/src/lib/p64 \
    -Ithird_party/vice-libretro/vice/src/monitor \
    -Ithird_party/vice-libretro/vice/src/raster \
    -Ithird_party/vice-libretro/vice/src/resid \
    -Ithird_party/vice-libretro/vice/src/residfp \
    -Ithird_party/vice-libretro/vice/src/residfp/builders/residfp-builder/residfp \
    -Ithird_party/vice-libretro/vice/src/rs232drv \
    -Ithird_party/vice-libretro/vice/src/rtc \
    -Ithird_party/vice-libretro/vice/src/samplerdrv \
    -Ithird_party/vice-libretro/vice/src/socketdrv \
    -Ithird_party/vice-libretro/vice/src/tape \
    -Ithird_party/vice-libretro/vice/src/tapeport \
    -Ithird_party/vice-libretro/vice/src/userport \
    -Ithird_party/vice-libretro/vice/src/vdrive \
    -Ithird_party/vice-libretro/vice/src/vicii \
    -Ithird_party/vice-libretro/vice/src/video

